from . import project_project_input
from . import project_report
from . import product_category
from . import product_template
from . import project_competitor
from . import project_customer
from . import project_distance
from . import project_project
from . import res_company
from . import res_country_district
from . import res_country_ward
from . import res_partner
from . import sale_order
from . import srdc_concrete_pump_category
from . import srdc_concrete_pump_volume
from . import srdc_floor_elevation
from . import sale_order_line
from . import srdc_contract
from . import srdc_io
from . import srdc_io_line
from . import srdc_plant
from . import srdc_tender_package
from . import srdc_type_of_pump
